/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ReadItem } from "./ReadItem";
import { ReadItemCountArgs } from "./ReadItemCountArgs";
import { ReadItemFindManyArgs } from "./ReadItemFindManyArgs";
import { ReadItemFindUniqueArgs } from "./ReadItemFindUniqueArgs";
import { DeleteReadItemArgs } from "./DeleteReadItemArgs";
import { ReadItemService } from "../readItem.service";
@graphql.Resolver(() => ReadItem)
export class ReadItemResolverBase {
  constructor(protected readonly service: ReadItemService) {}

  async _readItemsMeta(
    @graphql.Args() args: ReadItemCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ReadItem])
  async readItems(
    @graphql.Args() args: ReadItemFindManyArgs
  ): Promise<ReadItem[]> {
    return this.service.readItems(args);
  }

  @graphql.Query(() => ReadItem, { nullable: true })
  async readItem(
    @graphql.Args() args: ReadItemFindUniqueArgs
  ): Promise<ReadItem | null> {
    const result = await this.service.readItem(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ReadItem)
  async deleteReadItem(
    @graphql.Args() args: DeleteReadItemArgs
  ): Promise<ReadItem | null> {
    try {
      return await this.service.deleteReadItem(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
