/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Star } from "./Star";
import { StarCountArgs } from "./StarCountArgs";
import { StarFindManyArgs } from "./StarFindManyArgs";
import { StarFindUniqueArgs } from "./StarFindUniqueArgs";
import { DeleteStarArgs } from "./DeleteStarArgs";
import { StarService } from "../star.service";
@graphql.Resolver(() => Star)
export class StarResolverBase {
  constructor(protected readonly service: StarService) {}

  async _starsMeta(
    @graphql.Args() args: StarCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Star])
  async stars(@graphql.Args() args: StarFindManyArgs): Promise<Star[]> {
    return this.service.stars(args);
  }

  @graphql.Query(() => Star, { nullable: true })
  async star(@graphql.Args() args: StarFindUniqueArgs): Promise<Star | null> {
    const result = await this.service.star(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Star)
  async deleteStar(@graphql.Args() args: DeleteStarArgs): Promise<Star | null> {
    try {
      return await this.service.deleteStar(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
