/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Star as PrismaStar } from "@prisma/client";

export class StarServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.StarCountArgs, "select">): Promise<number> {
    return this.prisma.star.count(args);
  }

  async stars(args: Prisma.StarFindManyArgs): Promise<PrismaStar[]> {
    return this.prisma.star.findMany(args);
  }
  async star(args: Prisma.StarFindUniqueArgs): Promise<PrismaStar | null> {
    return this.prisma.star.findUnique(args);
  }
  async createStar(args: Prisma.StarCreateArgs): Promise<PrismaStar> {
    return this.prisma.star.create(args);
  }
  async updateStar(args: Prisma.StarUpdateArgs): Promise<PrismaStar> {
    return this.prisma.star.update(args);
  }
  async deleteStar(args: Prisma.StarDeleteArgs): Promise<PrismaStar> {
    return this.prisma.star.delete(args);
  }
}
