/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ReadHistory } from "./ReadHistory";
import { ReadHistoryCountArgs } from "./ReadHistoryCountArgs";
import { ReadHistoryFindManyArgs } from "./ReadHistoryFindManyArgs";
import { ReadHistoryFindUniqueArgs } from "./ReadHistoryFindUniqueArgs";
import { DeleteReadHistoryArgs } from "./DeleteReadHistoryArgs";
import { ReadHistoryService } from "../readHistory.service";
@graphql.Resolver(() => ReadHistory)
export class ReadHistoryResolverBase {
  constructor(protected readonly service: ReadHistoryService) {}

  async _readHistoriesMeta(
    @graphql.Args() args: ReadHistoryCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ReadHistory])
  async readHistories(
    @graphql.Args() args: ReadHistoryFindManyArgs
  ): Promise<ReadHistory[]> {
    return this.service.readHistories(args);
  }

  @graphql.Query(() => ReadHistory, { nullable: true })
  async readHistory(
    @graphql.Args() args: ReadHistoryFindUniqueArgs
  ): Promise<ReadHistory | null> {
    const result = await this.service.readHistory(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ReadHistory)
  async deleteReadHistory(
    @graphql.Args() args: DeleteReadHistoryArgs
  ): Promise<ReadHistory | null> {
    try {
      return await this.service.deleteReadHistory(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
